[package]
name = "vulkan"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../../api" }
ard-log = { path = "../../../ard-log" }
arrayvec.workspace = true
arc-swap.workspace = true
crossbeam-channel.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
raw-window-handle.workspace = true
crossbeam-utils.workspace = true
dashmap.workspace = true
rustc-hash.workspace = true
unsafe_unwrap.workspace = true
smallvec.workspace = true
puffin.workspace = true
ash = "0.38"
ash-window = "0.13"
gpu-allocator = { git = "https://github.com/Traverse-Research/gpu-allocator.git", branch = "ash-0.38", features = [ "vulkan" ], default-features = false }