[package]
name = "vulkan"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../../api" }
crossbeam-channel.workspace = true
thiserror.workspace = true
bytemuck.workspace = true
raw-window-handle.workspace = true
crossbeam-utils.workspace = true
dashmap.workspace = true
rustc-hash.workspace = true
unsafe_unwrap.workspace = true
smallvec.workspace = true
ash = "0.37.1"
ash-window = "0.12"
gpu-allocator = "0.24"