[package]
name = "editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = [ "rt-multi-thread" ] }
ard-engine = { path = "../../", version = "0.1" }
egui_dock = "0.3"
egui = { version = "0.20", features = ["bytemuck"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
fs_extra = "1"
rand = "0.8"
ron = "0.8"
smallvec = { version = "1", features = ["serde"] }