[package]
name = "editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ard-engine = { path = "../../" }
tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
ron.workspace = true
smallvec.workspace = true
paste.workspace = true
egui.workspace = true
egui_dock = "0.3"
fs_extra = "1"
rand = "0.8"