[package]
name = "ard-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [ "crates/*" ]

[features]
default = [ "input", "assets", "graphics_vk", "window" ]
input = [ "ard-input" ]
assets = [ "ard-assets" ]
graphics_vk = [ "window", "ard-graphics-api", "ard-graphics-vk" ]
window = [ "ard-window", "ard-winit" ]

[dependencies]
# Required
ard-core = { path = "./crates/ard-core", version = "0.1" }
ard-ecs = { path = "./crates/ard-ecs", version = "0.1" }
ard-log = { path = "./crates/ard-log", version = "0.1" }
ard-math = { path = "./crates/ard-math", version = "0.1" }

# Optional
ard-input = { path = "./crates/ard-input", version = "0.1", optional = true }
ard-assets = { path = "./crates/ard-assets", version = "0.1", optional = true }
ard-graphics-api = { path = "./crates/ard-graphics-api", version = "0.1", optional = true }
ard-graphics-vk = { path = "./crates/ard-graphics-vk", version = "0.1", optional = true }
ard-window = { path = "./crates/ard-window", version = "0.1", optional = true }
ard-winit = { path = "./crates/ard-winit", version = "0.1", optional = true }

[dev-dependencies]
bytemuck = "1.7"