/// DO NOT MODIFY: Autogenerated by `build.rs`

pub(crate) const FRAMES_IN_FLIGHT: usize = 2;
pub(crate) const FROXEL_TABLE_DIMS: (usize, usize, usize) = (32, 18, 16);
pub(crate) const MAX_LIGHTS_PER_FROXEL: usize = 256;
pub(crate) const MAX_TEXTURES_PER_MATERIAL: usize = 8;
pub(crate) const NO_TEXTURE: u32 = 4294967295;
pub(crate) const MAX_SHADOW_CASCADES: usize = 4;
