[package]
name = "ard-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ard-engine = { path = "../../" }
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
thiserror.workspace = true
ron.workspace = true
smallvec.workspace = true
paste.workspace = true
egui.workspace = true
egui-phosphor.workspace = true
rustc-hash.workspace = true
crossbeam-channel.workspace = true
fs_extra.workspace = true
egui_tiles = "0.8"
tempfile = "3.10"
path_macro = "1.0.0"