[package]
name = "ard-log"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log-panics = "2.1"
log4rs = "1.1"
chrono = "0.4"