[package]
name = "ibl_baker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] }
glium = "0.31"
image = "0.24"
glam = "0.20"

[workspace]