[package]
name = "ard-winit"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ard-ecs = { path = "../ard-ecs" }
ard-core = { path = "../ard-core" }
ard-window = { path = "../ard-window" }
ard-input = { path = "../ard-input" }
ard-math = { path = "../ard-math" }
winit.workspace = true