[package]
name = "ard-winit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25"
glam = "0.18"
ard-ecs = { version = "0.1", git = "ssh://git@github.com/ReeCocho/ard-ecs.git", branch = "main" }
ard-core = { version = "0.1", git = "ssh://git@github.com/ReeCocho/ard-core.git", branch = "main" }
ard-window = { version = "0.1", git = "ssh://git@github.com/ReeCocho/ard-window.git", branch = "main" }
ard-input = { version = "0.1", git = "ssh://git@github.com/ReeCocho/ard-input.git", branch = "main" }