[package]
name = "ard-winit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27"
glam = "0.18"
ard-ecs = { version = "0.1", path = "../ard-ecs" }
ard-core = { version = "0.1", path = "../ard-core" }
ard-window = { version = "0.1", path = "../ard-window" }
ard-input = { version = "0.1", path = "../ard-input" }