[package]
name = "ibl-oven"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = [ "derive" ] }
ard-pal = { path = "../../crates/ard-pal", version = "0.1" }
ard-math = { path = "../../crates/ard-math", version = "0.1" }
ard-formats = { path = "../../crates/ard-formats", version = "0.1" }
intel_tex_2 = "0.2"
rayon = "1"
image = "0.24"
bytemuck = "1"
bincode = "1"
winit = "0.27"
ordered-float = "3"