[package]
name = "ibl-oven"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ard-pal = { path = "../../crates/ard-pal" }
ard-math = { path = "../../crates/ard-math" }
ard-formats = { path = "../../crates/ard-formats" }
rayon.workspace = true
image.workspace = true
bytemuck.workspace = true
bincode.workspace = true
winit.workspace = true
intel_tex_2 = "0.2"
ordered-float = "3"
clap = { version = "4", features = [ "derive" ] }