#ifndef _CONSTANTS_GLSL
#define _CONSTANTS_GLSL
#define FROXEL_TABLE_X 32
#define FROXEL_TABLE_Y 18
#define FROXEL_TABLE_Z 16
#define MAX_POINT_LIGHTS_PER_FROXEL 256
#define MAX_TEXTURES_PER_MATERIAL 8 
#define NO_TEXTURE 4294967295
#endif
