[package]
name = "ard-window"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ard-ecs = { path = "../ard-ecs" }
ard-core = { path = "../ard-core" }
ard-math = { path = "../ard-math" }